import "~/styles/globals.css";

import { Outfit } from "next/font/google";
import { headers } from "next/headers";
import { TRPCReactProvider } from "~/trpc/react";
import { Themeprovider } from "./_components/index";
import { ToastContainer } from "../lib/myToast";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`font-outfit bg-theme text-revert-theme ${outfit.variable}`}
      >
        <ToastContainer position="top-center" />
        <TRPCReactProvider headers={headers()}>
          <Themeprovider>{children}</Themeprovider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
