import "~/styles/globals.css";

import { Outfit } from "next/font/google";
import { headers } from "next/headers";
import { TRPCReactProvider } from "~/trpc/react";
import { Themeprovider } from "~/ui";
import { ToastContainer } from "../lib/myToast";
import { getServerAuthSession } from "../server/auth";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-theme  text-revert-theme ${outfit.variable}`}>
        <TRPCReactProvider headers={headers()}>
          <Themeprovider>
            <ToastContainer position="top-center" />

            {children}
          </Themeprovider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
